### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by cheziyi** [sarathsurpur/STRESS-TESTING#1]
- [x] For inserts, it should be done in batches, i.e. INSERT INTO table (a, b, c) VALUES (1,2,3), (4,5,6)...
- [x] Add support for MSSQL as well
- [x] Add multithreading (multiple simultaneous connections): each connection should perform their queries simultaneously with other connections
- [x] Add consecutive connections: a new connection will be started after a connection has finished all it's queries, and repeat them
- [x] Add UPDATE queries
- [x] Add console display & logging to a text file for all errors that occurred (With the query, and error message)
- [x] Add console display & logging for time taken for each set of queries
- [x] Add in command line options for:
  - [ ] MySQL or MSSQL
  - [ ] Connection details (ip, port, database, username, password)
  - [ ] Number of threads
  - [ ] Number of consecutive connections
  - [ ] Number of rows per insert
  - [ ] Queries to run and the number of each of them to run (only CREATE, INSERTs, SELECTs, UPDATEs, ENCRYPTs, DECRYPTs, DROP or combination of them, and number)

**Comment by sarathsurpur** [comment]
updated insert statement in code
